# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_floor', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers_floor', models.IntegerField(default=0)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_plans.Edge')),
            ],
        ),
        migrations.CreateModel(
            name='TypeofDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('building', models.CharField(choices=[(b'MARKET', b'Market'), (b'COMPANY', b'Company'), (b'HOSPITAL', b'Hospital'), (b'OTHERS', b'Other')], default=b'OTHERS', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_origin_point', models.BooleanField(default=False)),
                ('nfc_code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('nfc_type', models.CharField(choices=[(b'YES', b'Yes'), (b'No', b'No')], default=b'NO', max_length=60)),
                ('number_floor', models.IntegerField(default=0)),
                ('point_x', models.IntegerField(default=0)),
                ('point_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='vertex_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_vertex_one', to='design_plans.Vertex'),
        ),
        migrations.AddField(
            model_name='edge',
            name='vertex_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_vertex_two', to='design_plans.Vertex'),
        ),
        migrations.AddField(
            model_name='designplans',
            name='map',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='design_plans.Map'),
        ),
        migrations.AddField(
            model_name='designplans',
            name='type_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_plans.TypeofDesign'),
        ),
    ]
